# --------------------------------------
# ✅ Site Settings
# --------------------------------------
title: Praduman Pandey
tagline: Magento 2 Developer
theme: jekyll-theme-cayman
repository: praduman-pandey/portfolio
baseurl: "/portfolio"                          # Leave empty if deploying to root

# --------------------------------------
# ✅ Plugin Configuration
# --------------------------------------
plugins:
  - jekyll-sitemap                        # Generates sitemap.xml
  # - jekyll-feed                         # (Optional) Adds RSS feed
  - jekyll-seo-tag                        # (Optional) Adds SEO metadata

# --------------------------------------
# ✅ Site-wide Toggles
# --------------------------------------
google_analytics: false
show_services: false
content_enabled: false

# --------------------------------------
# ✅ SEO & Webmaster Verification
# --------------------------------------
webmaster_verifications:
  google: dHUZ669byNdjEg1LNiG8KH97Falj8b0JyYc7f32yayg

# --------------------------------------
# ✅ Layout Defaults
# --------------------------------------
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
