plugins:
  - jekyll-sitemap
  
title: Praduman Pandey
tagline: Magento 2 Developer
google_analytics: false
show_services: false
content_enabled: false
webmaster_verifications:
  google: 6GYK-fIj4-GOXib2LrrHEg_UJbCy6BcvnicY4gr1XRE
theme: jekyll-theme-cayman
repository: praduman-pandey/portfolio

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      